[package]
name = "markdown_img_url_editor_rust"
version = "0.1.0"
authors = ["yumetodo <yume-wikijp@live.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.5.3"
pulldown-cmark-to-cmark = "1.2.2"
wasm-bindgen = "0.2.50"
wasm-bindgen-futures = "0.3.27"
js-sys = "0.3.27"
futures = "0.1.28"

[lib]
crate-type = ["cdylib"]
