language: node_js
node_js:
- lts/*
cache: npm
script:
- npm run lint
- npm test
deploy:
  provider: npm
  email: yume-wikijp@live.jp
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: rr+I/hNf94B3PQr/m14kUQe1PA8fftvByYZhS3FrDMA0hmi75GcEg1lOXZ4VhfAob7galG2HjTAObIqjEutOYzRgT8VdWx2v6Vir2AfZBvD6IDrjTp5A9sm4tu26FM3x2IqKMRxpS5n7TM3It1iNwooxmMj77J28gqbCuh8Bq9nz9wlwyfPh6ZEl9jl1Nzb2ZipULTVVc+bpGDNKSlZFTe8Rs+DlZQJX5YEoYjwLYY+H2MJ4qyX3R1kTXN96Tr09hxnXrLxuoYLIEYfOn+e6pEI3zjGET1/V0vdfAQut0Z5WB7GwT1/l+LUc2e/Sh85WGhQ9qLJvVWbCBvVl7nTYWRcdGZm+waV8CUmUoCcOBvSS0Fyg0JGsA8CG3pA5O+QWukinCbMWitrVGPd7bZJWwBynnJW8THiAI1BxwJaauQL1jd2GmGJPpO5kcMJs9ULoRNLtg7OhH/nlmHIAthjxs3ZD3vaS//pe7lQ+r+Uc03HmWdM6tF5h9I8MfC/CF2uZY1kF/mfYPpg2Av/BLofHFZUW+YRj9w6X7O4UZAXYhLNFI0ruHMlcUYQkaQyU3H68drQ5Rb6wsNj12CGl4yDfZLHxXtsF933SW/jsw3e8yjRHu+jxjwJbBsvIXg62JcSYvB1PtZdiYlv5vnPBOXmQqFHnsL6o5iyBtFG9gYHfyYo=
