version: 2.1
executors:
    default:
        docker:
            - image: yumetodo/buildcontainers:rust-latest-wasm-lts
        working_directory: ~/repo
commands:
    npm_install:
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: npm ci
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
    tool_install:
        steps:
            - run: npm i -g can-npm-publish
    cargo_restore_cache:
        steps:
            - run:
                name: Calculate dependencies
                command: cargo generate-lockfile
                working_directory: markdown_img_url_editor_rust
            - restore_cache:
                keys:
                  - v4-cargo-cache-{{ arch }}-{{ checksum "markdown_img_url_editor_rust/Cargo.lock" }}
    cargo_save_cache:
        steps:
            - save_cache:
                paths:
                  - /usr/local/cargo/registry
                  - markdown_img_url_editor_rust/target/debug/.fingerprint
                  - markdown_img_url_editor_rust/target/debug/build
                  - markdown_img_url_editor_rust/target/debug/deps
                  - markdown_img_url_editor_rust/target/release/.fingerprint
                  - markdown_img_url_editor_rust/target/release/build
                  - markdown_img_url_editor_rust/target/release/deps
                key: v4-cargo-cache-{{ arch }}-{{ checksum "markdown_img_url_editor_rust/Cargo.lock" }}
jobs:
    test:
        executor: default
        steps:
            - npm_install
            - cargo_restore_cache
            - run: npm run build
            - run: npm test
            - run: npm run build:release
            - run: npm test
            - cargo_save_cache
    publish:
        executor: default
        steps:
            - tool_install
            - npm_install
            - cargo_restore_cache
            - run: npm run build:release
            - cargo_save_cache
            - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
            - run:
                command: |
                    if can-npm-publish; then
                        npm publish
                    else
                        echo "publish skipped"
                    fi
workflows:
    version: 2
    publishflow:
        jobs:
            - test
            - publish:
                context: npm
                requires:
                    - test
                filters:
                    tags:
                        only: /^v.*/
