version: 2.1
executors:
    default:
        docker:
            - image: circleci/node:lts
        working_directory: ~/repo
commands:
    npm_install:
        steps:
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: npm ci
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
    tool_install:
        steps:
            - run: npm i -g can-npm-publish
jobs:
    test:
        executor: default
        steps:
            - checkout
            - npm_install
            - run: npm run build
            - run: npm test
            - persist_to_workspace:
                root: ~/repo
                paths:
                    - dist
    publish:
        executor: default
        steps:
            - tool_install
            - checkout
            - attach_workspace:
                at: ~/repo
            - run: npm ci
            - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
            - run:
                command: |
                    if can-npm-publish --verbose; then
                        npm publish
                    else
                        echo "publish skipped"
                    fi
workflows:
    version: 2
    publishflow:
        jobs:
            - test
            - publish:
                context: npm
                requires:
                    - test
                filters:
                    tags:
                        only: /^v.*/
