version: 2.1
executors:
    default:
        docker:
            - image: yumetodo/buildcontainers:rust-latest-wasm-lts
        working_directory: ~/repo
commands:
    npm_install:
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json" }}
                    - v1-dependencies-
            - run: npm ci
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json" }}
    tool_install:
        steps:
            - run: sudo npm i -g can-npm-publish
jobs:
    test:
        executor: default
        steps:
            - npm_install
            - run: npm run build
            - run: npm test
            - run: npm run build:release
            - run: npm test
    publish:
        executor: default
        steps:
            - tool_install
            - npm_install
            - run: npm run build:release
            - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
            - run:
                command: |
                    if can-npm-publish; then
                        npm publish
                    else
                        echo "publish skipped"
                    fi
workflows:
    version: 2
    build_and_test:
      jobs:
        - test
    publishflow:
        jobs:
            - test:
                context: npm
                filters:
                    branches:
                        only:
                            - master
            - publish:
                context: npm
                requires:
                    - test
                filters:
                    branches:
                        only:
                            - master